// <auto-generated />
using Animals.EF.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animals.Api.Migrations
{
    [DbContext(typeof(AnimalDbContext))]
    [Migration("20220515210729_speciesMigration")]
    partial class speciesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Animals.Core.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name")
                        .HasColumnOrder(2);

                    b.Property<int>("Specie_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Specie_Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Animals.Core.Models.Specie", b =>
                {
                    b.Property<int>("Specie_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Specie_Id"), 1L, 1);

                    b.Property<string>("SpecieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Specie_Id");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Animals.Core.Models.Animal", b =>
                {
                    b.HasOne("Animals.Core.Models.Specie", "Specie")
                        .WithMany("Animals")
                        .HasForeignKey("Specie_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specie");
                });

            modelBuilder.Entity("Animals.Core.Models.Specie", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
